version: "3"

services:

  app:
    environment:
      - ec2-prod.env
    image: app:${APP_VERSION}
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "0.25"
    #          memory: 1024M
    #        reservations:
    #          cpus: "0.10"
    #          memory: 512M
    ports:
      - "8080:8080"
    networks:
      - my-net

  prometheus:
    environment:
      - ec2-prod.env
    image: prom/prometheus:${PROM_VERSION}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-net

  grafana:
    environment:
      - ec2-prod.env
    image: grafana/grafana:${GRAF_VERSION}
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - my-net

networks:
  my-net:
    external: true
    driver: overlay