version: "3"
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    container_name: "mongodb"
    ports:
      - "27017:27017"
  app:
    image: practice-board
    ports:
      - "8080:8080"
    links:
      - mongodb
#  prometheus:
#    image: prom/prometheus:latest
#    ports:
#      - "9090:9090"