version: "3"
services:
  mongodb:
    image: mongo:5.0.9
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    image: practice-board
    ports:
      - 5000:5000
    links:
      - mongodb