global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "host.docker.internal:9090" ]
  - job_name: "ojt-board"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "app:8081" ]