version: 2.1
executors:
  java:
    docker:
      - image: cimg/openjdk:11.0.13
    resource_class: medium

jobs:
  gradle-build:
    executor: java
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: build/libs
  docker-build:
    executor: java
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
      - run: docker login -u beenkim -p $DOCKER_HUB_PASSWORD
      - run: docker build -t springbootcicdtest/build-image .
      - run: docker tag springbootcicdtest/build-image
      - run: docker push beenkim/springbootcicdtest
      - run: sudo apt-get update

workflows:
  main-branch-workflow:
    jobs:
      - gradle-build:
          filters: &filters-main
            branches:
              only: main
            tags:
              ignore: /.*/
  tag-workflow:
    jobs:
      - gradle-build:
          filters: &filters-ops
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker-build:
          requires:
            - gradle-build
          filters:
            <<: *filters-ops
