# Java Gradle CircleCI 2.0 configuration file
version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      #      - run: gradle test
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs
      - setup_remote_docker
      - version: 20.10.14
      - run: docker build --build-arg JAR_FILE=build/libs/docker-0.0.1-SNAPSHOT.jar --tag beenkim/cicd-test .
      - run: docker login -u beenkim -p $DOCKER_HUB_PASSWORD
      - run: docker push beenkim/springbootcicdtest
      - run: sudo apt-get update
