version: 2.1
executors:
  java:
    docker:
      - image: cimg/openjdk:11.0.13
    resource_class: medium

jobs:
  gradle-build:
    executor: java
    working_directory: ~/tmp
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
  docker-build:
    executor: java
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run: docker build -t beenkim/springbootcicd .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/springbootcicd

workflows:
  main-branch-workflow:
    jobs:
      - gradle-build:
          context: user-info
          filters: &filters-main
            branches:
              only: main
            tags:
              ignore: /.*/
      - docker-build:
          context: user-info
          requires:
            - gradle-build
          filters: &filters-main
            branches:
              only: main
            tags:
              ignore: /.*/