version: 2.1
executors:
  java:
    docker:
      - image: cimg/openjdk:11.0.13
    resource_class: medium

jobs:
  gradle-build:
    executor: java
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  docker-build:
    executor: java
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          command: |
            echo "Build docker image"
            TAG=$(git log -1 --pretty=%h)
            docker build -t $REPO_NAME:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $REPO_NAME:$TAG
#      - run:
#          command: |
#            echo "Build image of service declared in docker-compose"
#            docker-compose up --build -d

workflows:
  main-branch-workflow:
    jobs:
      - gradle-build:
          filters: &filters-main
            branches:
              only: main
            tags:
              ignore: /.*/
  tag-workflow:
    jobs:
      - gradle-build:
          filters: &filters-ops
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker-build:
          context: user-info
          requires:
            - gradle-build
          filters:
            <<: *filters-ops
