version: 2.1
executors:
  java:
    docker:
      - image: cimg/openjdk:11.0.13
    resource_class: medium

jobs:
  gradle-build:
    executor: java
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  docker-build:
    executor: java
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: Build docker image and push to docker hub
          command: |
            docker build -t app .
            LAST_TAG=$(git log -1 --pretty=%h)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag app $REPO_NAME:$LAST_TAG
            docker push $REPO_NAME:$LAST_TAG
  deploy-ec2:
    executor: java
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "83:f6:df:5a:a7:d7:0a:6c:fb:ad:e0:55:4c:c0:be:37"
      - run:
          name: Version for images
          command: |
            APP_VERSION=$LAST_TAG
            PROM_VERSION="v2.37.0"
            GRAF_VERSION="9.0.4"
      - run:
          name: Deploy to ec2 instance
          command: |
            ssh -o "StrictHostKeyChecking no" ${AWS_EC2_USER_NAME}@ec2-${AWS_EC2_IP}.${AWS_EC2_REGION}.compute.amazonaws.com \<<'ENDSSH'
            rsync -ah -e docker-compose.yml ${AWS_EC2_USER_NAME}@ec2-${AWS_EC2_IP}.${AWS_EC2_REGION}.compute.amazonaws.com:~/spring-app/
            ENDSSH

  compose-run:
    executor: java
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: Run docker-compose
          command: |
            ssh ${AWS_EC2_USER_NAME}@ec2-${AWS_EC2_IP}.${AWS_EC2_REGION}.compute.amazonaws.com
            cd spring-app
            docker-compose up --build -d

workflows:
  main-branch-workflow:
    jobs:
      - gradle-build:
          filters: &filters-ops
            branches:
              only: main
            tags:
              only: /^v.*/
      - docker-build:
          context: docker-info
          requires:
            - gradle-build
          filters:
            <<: *filters-ops
      - deploy-ec2:
          context: aws-ec2
          requires:
            - docker-build
          filters:
            <<: *filters-ops
      - compose-run:
          context: aws-ec2
          requires:
            - deploy-ec2
          filters:
            <<: *filters-ops

